version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - vector_service
      - pinecone_service

  vector_service:
    build:
      context: ./vector_service
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
    ports:
      - "8001:8001"
    networks:
      - app-network

  pinecone_service:
    build:
      context: ./pinecone_service
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
    ports:
      - "8002:8002"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
