services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
      - PYTHONUNBUFFERED=1
      - PINECONE_SERVICE_HOST=pinecone_service  # Removed extra spaces
      - VECTOR_SERVICE_HOST=vector_service     # Removed extra spaces
    ports:
      - "${APP_PORT_BACKEND}:${APP_PORT_BACKEND}"
    networks:
      - app-network
    depends_on:
      - vector_service
      - pinecone_service

  vector_service:
    build:
      context: ./vector_service
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
      - PYTHONUNBUFFERED=1
    ports:
      - "${APP_PORT_VECTOR}:${APP_PORT_VECTOR}"
    networks:
      - app-network

  pinecone_service:
    build:
      context: ./pinecone_service
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
      - PYTHONUNBUFFERED=1
    ports:
      - "${APP_PORT_PINECONE}:${APP_PORT_PINECONE}"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production  # Ensure the app runs in production mode
    stdin_open: true  # Keep STDIN open for interactive mode (optional)
    tty: true         # Allocate a pseudo-TTY (optional)
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge