version: '3.8'
services:
  backend:
    build:
      context: ./backend
    environment:
      - PINECONE_API_KEY=your_pinecone_api_key
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
