services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - vector_service
      - pinecone_service

  vector_service:
    build:
      context: ./vector_service
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    networks:
      - app-network

  pinecone_service:
    build:
      context: ./pinecone_service
      dockerfile: Dockerfile
    volumes:
      - ../../../secrets:/secrets
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/secret.json
      - PYTHONUNBUFFERED=1
    ports:
      - "8002:8002"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production  # Ensure the app runs in production mode
    stdin_open: true  # Keep STDIN open for interactive mode (optional)
    tty: true         # Allocate a pseudo-TTY (optional)
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
