name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Python Linting with Flake8 across all relevant folders
      - name: Install Python and Flake8
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Change this to a valid version
      - run: |
          pip install flake8
          flake8 src/caption src/finetune src/inference src/scraper src/server/vector_service src/server/pinecone_service src/vectorized_db_init --count --select=E9,F63,F7,F82 --show-source --statistics

      # # React Linting with ESLint for Frontend
      # - name: Install Node.js and ESLint
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      # - run: |
      #     cd src/server/frontend
      #     npm install
      #     npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker Images for each service
      - name: Build Caption Service
        run: docker build -t caption:latest src/caption/
      - name: Build Finetune Service
        run: docker build -t finetune:latest src/finetune/
      - name: Build Vectorized DB Init Service
        run: docker build -t vectorized_db_init:latest src/vectorized_db_init/
      - name: Build Scraper Service
        run: docker build -t scraper:latest src/scraper/
      - name: Build Backend Service
        run: docker build -t backend:latest src/server/backend/
      - name: Build Pinecone Service
        run: docker build -t pinecone_service:latest src/server/pinecone_service/
      - name: Build Vector Service
        run: docker build -t vector_service:latest src/server/vector_service/
      - name: Build Frontend
        run: docker build -t frontend:latest src/server/frontend/