name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - src/caption
          - src/finetune
          - src/inference
          - src/scraper
          - src/server/vector_service
          - src/server/pinecone_service
          - src/vectorized_db_init
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python and Flake8
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          cd ${{ matrix.service }}
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - src/caption
          - src/finetune
          - src/vectorized_db_init
          - src/scraper
          - src/server/backend
          - src/server/pinecone_service
          - src/server/vector_service
          - src/server/frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image for ${{ matrix.service }}
        run: docker build -t ${{ matrix.service##*/ }}:latest ${{ matrix.service }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - src/caption
          - src/finetune
          - src/scraper
          - src/vectorized_db_init
          - src/server/backend
          - src/server/pinecone_service
          - src/server/vector_service
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python and pipenv
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: pip install pipenv

      - name: Install Dependencies for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          pipenv install --dev

      - name: Run Tests for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          pipenv run pytest --cov=. --cov-report=xml --cov-fail-under=50

      - name: Upload Coverage Report for ${{ matrix.service }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.service##*/ }}
          path: ${{ matrix.service }}/coverage.xml
