name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Python Linting with Flake8 across all relevant folders
      - name: Install Python and Flake8
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          pip install flake8
          flake8 caption finetune inference scraper server/vector_service server/pinecone_service vectorized_db_init --count --select=E9,F63,F7,F82 --show-source --statistics

      # React Linting with ESLint for Frontend
      - name: Install Node.js and ESLint
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd server/frontend
          npm install
          npm run lint